name: Run E2E Tests

on: [pull_request]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      api:
        build:
          context: .
          dockerfile: Dockerfile.dev
        restart: unless-stopped
        init: true
        environment:
          - "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
        ports:
          - 3333:3333
        volumes:
          - .:/app
          - /app/node_modules
        depends_on:
          - postgres
        extra_hosts:
          - "host.docker.internal:host-gateway"
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"
